version: 2.0

jobs:
  build:
    docker:
      - image: circleci/python:2.7-stretch-browsers
    steps:
      - checkout
      - run: "curl -fsSL https://testspace-client.s3.amazonaws.com/testspace-linux.tgz | sudo tar -zxvf- -C /usr/local/bin"
      - run: "testspace config url samples.testspace.com"
      - run: "sudo pip install -r requirements.txt"
      - run: "sudo apt-get install pylint"
      - run: "pylint stock_alerter/ -f parseable > analysis.txt || true"
      - run: "nose2 --junit-xml --with-coverage"
      - run:
          name: Send reports to testspace
          command: "testspace analysis.txt{lint} nose2.xml{stock_alerter} coverage.xml"
          when: always
