name: Build
on:
  push:
  schedule:
    - cron:  '0 1 * * 0'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 2.7
      - name: Setup build tools
        run: |
          sudo apt-get install pylint
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - uses: testspace-com/setup-testspace@v1
        with:
          domain: samples
      - name: Install
        run: |
          pip install -r requirements.txt
      - name: Analyze
        run: |
          pylint stock_alerter/ -f parseable > analysis.txt || true
      - name: Test
        run: |
          nose2 --junit-xml --with-coverage
      - name: Push
        run: |
          testspace analysis.txt{lint} nose2.xml{stock_alerter} coverage.xml
        if: always()
